apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  template:
    metadata:
    spec:
      containers:             
      - name: nn
        image: 881986476278.dkr.ecr.us-east-2.amazonaws.com/nn:__IMAGE_TAG__       
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.2" 