trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  system.debug: true
  ecr: '881986476278.dkr.ecr.us-east-2.amazonaws.com'
  ecr_repo: 'nn'
  ecr_conn: 'azure_devops_to_ecr_docker_conn'
  trivy: 'aquasec/trivy:0.71.2'
  cosign: 'ghcr.io/sigstore/cosign/cosign:latest'
      
stages:
- stage: Build
  displayName: 'Build and Scan'
  jobs:
  - job: Build
    displayName: 'Build and Scan Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Building Docker Image'
      inputs:
        containerRegistry: $(ecr_conn)
        repository: $(ecr_repo)
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.BuildId)
          
    - script: |
        docker --version
        docker buildx version
        docker save $(ecr)/$(ecr_repo):$(Build.BuildId) -o $(Build.ArtifactStagingDirectory)/$(ecr_repo).tar
        echo $(ecr)/$(ecr_repo):$(Build.BuildId)
        docker inspect $(ecr)/$(ecr_repo):$(Build.BuildId)
        docker build -t $(ecr)/$(ecr_repo):$(Build.BuildId) -f '$(Build.SourcesDirectory)/Dockerfile' $(Build.SourcesDirectory)
        docker inspect $(ecr)/$(ecr_repo):$(Build.BuildId)
        docker inspect --format='{{.Descriptor.digest}}' $(ecr)/$(ecr_repo):$(Build.BuildId) | tee $(Build.ArtifactStagingDirectory)/digest.txt
      displayName: 'Saving Docker Image'

    - task: PublishPipelineArtifact@1
      displayName: 'Publishing Docker Image as Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(ecr_repo).tar'
        artifactName: 'docker-image-$(ecr_repo)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publishing Docker Image Digest as Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/digest.txt'
        artifactName: 'docker-image-digest-$(ecr_repo)'
          
- stage: Scan
  displayName: 'Scanning Docker Image'
  dependsOn: Build
  jobs:
  - job: Scan
    steps:
    - task: DownloadPipelineArtifact@1
      displayName: 'Downloading Image Artifact'
      inputs:
        artifactName: 'docker-image-$(ecr_repo)'
        targetPath: '$(Pipeline.Workspace)'

    - script: |
        docker load -i $(Pipeline.Workspace)/$(ecr_repo).tar
      displayName: 'Loading Docker Image'

    - task: Docker@2
      displayName: 'Scanning Docker Image OS'
      inputs:
        command: 'run'
        arguments: |
          -v /var/run/docker.sock:/var/run/docker.sock
          $(trivy) image $(ecr)/$(ecr_repo):$(Build.BuildId)
          --severity CRITICAL
          --exit-code 1
      continueOnError: false

    - task: Docker@2
      displayName: 'Scanning Docker Image Application Dependencies'
      enabled: false
      inputs:
        command: 'run'
        arguments: |
          -v $(Build.SourcesDirectory):/src
          -v /var/run/docker.sock:/var/run/docker.sock
          $(trivy) fs /src
          --severity CRITICAL
          --exit-code 1
      continueOnError: false       
          
- stage: Push
  displayName: 'Pushing Docker Image'
  dependsOn: Scan
  jobs:
  - job: Push
    steps:
    - task: DownloadPipelineArtifact@1
      displayName: 'Downloading Image Artifact'
      inputs:
        artifactName: 'docker-image-$(ecr_repo)'
        targetPath: '$(Pipeline.Workspace)'

    - script: |
        docker load -i $(Pipeline.Workspace)/$(ecr_repo).tar
        docker tag $(ecr)/$(ecr_repo):$(Build.BuildId) $(ecr)/$(ecr_repo):latest
      displayName: 'Loading Docker Image, and Tagging with "latest"'

    - task: Docker@2
      displayName: 'Pushing Docker Image to ECR'
      inputs:
        command: push
        containerRegistry: $(ecr_conn)
        repository: $(ecr_repo)
        tags: |
          latest
          $(Build.BuildId)
          
- stage: Sign
  displayName: 'Signing Docker Image'
  dependsOn: Push
  jobs:
  - job: Sign
    steps:
    - task: DownloadPipelineArtifact@1
      displayName: 'Downloading Image Digest Artifact'
      inputs:
        artifactName: 'docker-image-digest-$(ecr_repo)'
        targetPath: '$(Pipeline.Workspace)'

    - script: |
        digest=`<$(Pipeline.Workspace)/digest.txt`
        echo "##vso[task.setvariable variable=digest]$digest"
      displayName: 'Getting the Digest of the Image'
      
    - task: Docker@2
      displayName: 'Login to ECR'
      inputs:
        command: 'login'
        containerRegistry: '$(ecr_conn)'
    
    - script: |
        docker pull $(ecr)/$(ecr_repo)@$(digest)
      displayName: Test ECR Access
        
    - task: Docker@2
      displayName: 'Signing Docker Image with Cosign'
      inputs:
        command: 'run'
        arguments: |
          -v /var/run/docker.sock:/var/run/docker.sock
          $(cosign) sign $(ecr)/$(ecr_repo)@$(digest)
        