trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  ecr: '881986476278.dkr.ecr.us-east-2.amazonaws.com'
  ecr_repo: 'nn'
  ecr_conn: 'azure_devops_to_ecr_docker_conn'
  trivy: 'aquasec/trivy:0.71.2'
      
stages:
- stage: BuildAndScan
  displayName: 'Build and Scan'
  jobs:
  - job: BuildAndScanImage
    displayName: 'Build and Scan Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Building Docker Image'
      inputs:
        containerRegistry: $(ecr_conn)
        repository: 'nn'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(Build.BuildId)

    - task: Docker@2
      condition: succeeded()
      displayName: 'Scanning Docker Image'
      inputs:
        command: 'run'
        arguments: |
          -v /var/run/docker.sock:/var/run/docker.sock
          $(trivy) image $(ecr)/$(ecr_repo):$(Build.BuildId)
          --severity CRITICAL
          --exit-code 1
      continueOnError: false