trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'azure_devops_to_ecr_docker_conn'
    repository: 'nn'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
      
- task: Docker@2
  displayName: 'Scan with Trivy'
  inputs:
    command: 'run'
    containerRegistry: ''  
    repository: 'aquasec/trivy:0.71.2'
    volumes: |
      /var/run/docker.sock:/var/run/docker.sock
    arguments: |
      -v /var/run/docker.sock:/var/run/docker.sock
      aquasec/trivy:0.71.2 image 881986476278.dkr.ecr.us-east-2.amazonaws.com/nn:$(Build.BuildId)
      --severity CRITICAL
      --exit-code 1